# 			Makefile docuementation
#
# 		This file is for running test cases
# Notes
# ------
# The following commands are useful when making single test
# ```python
# export PYTHONIOENCODING=utf-8
# export PYTHONUNBUFFERED=x
# python -m pytest -s tests/model/test_overfit.py
# ```

# test: prepare
test:
	pytest ./tests/

# .PHONY : prepare
# prepare:
# 	python tests/prepare_testdata.py

